set langmenu=ko_KR.UTF-8
let $LANG='ko_KR.UTF-8'
colorscheme peachpuff
syntax on
set cursorline
"color molokai
set showmode
set showmatch
set incsearch
set hlsearch
set lsp=5

if has('statusline')
    set laststatus=2

    " Broken down into easily includeable segments
    set statusline=%<%f\    " Filename
    set statusline+=%w%h%m%r " Options
    "set statusline+=%{fugitive#statusline()} "  Git Hotness
    set statusline+=\ [%{&ff}/%Y]            " filetype
    set statusline+=\ [%{getcwd()}]          " current dir
    set statusline+=\ [A=\%03.3b/H=\%02.2B] " ASCII / Hexadecimal value of char
    set statusline+=%=%-14.(%l,%c%V%)\ %p%%  " Right aligned file nav info
endif

set wrap                      " wrap long lines
set autoindent                  " indent at the same level of the previous line
set shiftwidth=4                " use indents of 4 spaces
"set expandtab            " tabs are spaces, not tabs
set tabstop=4      " an indentation every four columns
set softtabstop=4     " let backspace delete indent
set matchpairs+=<:>             " match, to be used with % 
set pastetoggle=<F12>           " pastetoggle (sane indentation on pastes)

set gdefault     " the /g flag on :s substitutions by default
set list
"set listchars=tab:~\ ,trail:.,extends:#,nbsp:. " Highlight problematic whitespace
set listchars=trail:⋅,nbsp:⋅,tab:~\ 
set viminfo='10,\"100,:30,%,n~/.viminfo
